{"command":"getPapersByKeyWords",
"query":"Accurate mobility \"location prediction\"", 
"max_google_papers":"100",
"max_researchgate_papers":"1",
"patents":"false", 
"citations":"false",
"http_contiguous_requests" : 5,
"sci_hub_captcha_retry_by_proxy_count" : 0,
"google_captcha_retry_by_proxy_count" : 0,
"commit_iterations" : 10,
"google_clusters_handling":"False",
"google_get_files":"True",
"google_sci_hub_files":"True",
"limit_resp_for_one_code" : 1
}